### ISSUE TITLE
CLASSPATH setup not working properly on Windows 10 (Python 3.6)

### ISSUE THREAD

**Issue by rensutheart** [imagej/imagej.py#11]
When trying to use ImageJ in Python (on Windows) using the following code:
`import imagej`
`ij = imagej.init('C:/(path to fiji)/fiji-win64/Fiji.app')`

I kept getting the following error:
`jnius.JavaException: Class not found b'net/imagej/ImageJ'`

I ended up scratching and realized that my jars were not being added properly to the classpath.

The root of the problem was line 55 in imagej.py
https://github.com/imagej/imagej.py/blob/f7dd08ac6e237c34b0bbf07b5795d08bf62a9f4d/imagej/imagej.py#L55

After changing the colon : to a semi-colon ; like this:  `jnius_config.add_classpath(";".join(jars))` everything worked perfectly. 

I realize this is a Windows specific error, but maybe have a simple conditional that checks the operating system.

**Comment by ctrueden** [comment]
Thanks for the report, @rensutheart. I pushed a fix that uses `os.pathsep`.

Relatedly: did you see [this comment](https://github.com/imagej/imagej.py/issues/6#issuecomment-409712266) about the file separators as well (`/` vs. `\`)? Just to confirm: you say the code worked perfectly _without_ the use of `os.sep` for file separators, correct?

**Comment by rensutheart** [comment]
Hi @ctrueden, well done for the fix.

I did see the comment, and I didn't encounter any of those issues, but it might be since I just use the "/" in Python for all my paths, which also works on Windows.

**Comment by mpinkert** [comment]
@ctrueden just another confirmation that this works fine on Windows.  It's okay to close the file-separators branch.

A thought for the future: the [pathlib library](https://docs.python.org/3/library/pathlib.html) is a popular way to do paths, as it handles operating system specific cases and offers some neat functionality (getting extension, file name, file name without the extension, parent folders, etc...)  Only downside is that most packages don't know what it is and you need to wrap the resulting variable in str().  It works fine with os though.

**Comment by ctrueden** [comment]
Thanks @mpinkert. I deleted the `file-separators` branch.
