### ISSUE TITLE
Recurring install error: "No matching distribution found for imglib2-imglyb" (from -r requirements.txt)

### ISSUE THREAD

**Issue by batlike** [imagej/imagej.py#7]
Using conda to install imglib2-imglyb is straightforward but installing the requirements for imagej.py always throws this error - that there are no matching distribution found for imglib2-imglyb. Any suggestions?

**Comment by ctrueden** [comment]
@batlike Sorry for the delay in reply.

Could you please post the commands you are running to install `imagej.py`, along with the output including the error message? Then I can try to reproduce and investigate.

**Comment by ctrueden** [comment]
@batlike I expect this issue has been resolved with the release of imagej 0.3.0 on PyPI. Please reopen if not, with details requested above.
